### ISSUE TITLE
Registration updates

### ISSUE THREAD

**Issue by dschwen** [jessecarterMOOSE/PRARIEDOG#185]
To work with https://github.com/idaholab/moose/pull/24225 PARAIEDOG needs some updates. 

Also the code is super outdated. I have a PR that takes it forward into the current century, but I'd appreciate it if @jessecarterMOOSE could think about whether the app is still used and needed, or should be taken out of Civet testing.

**Comment by jessecarterMOOSE** [comment]
@dschwen Civet testing is no longer needed for this app

**Comment by dschwen** [comment]
Ok, I'll pass on the message. Let me know if you need to reactivate the app at any point. I'd be happy to help you get it up to speed again.
